version: '3'
services:
  app:
    build: ./docker
    ports:
      - 3000:3000
    environment:
      - WORKDIR=/workspace
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
